---

#debug variabls
- name: Debug variables here
  debug:
    msg: "{{ hostvars['localhost'] }}"

# Install controller agent on NGINX+
- name: Get NGINX Controller API key for agent registration
  uri:
    url: "https://{{ controller_fqdn }}/{{ api_version }}/platform/global"
    method: "GET"
    return_content: yes
    status_code: 200
    validate_certs: false
    headers:
      Cookie: "{{ controller_auth_token }}"
  register: ctrl_globals

- name: Copy api_key to a variable
  set_fact:
    api_key: "{{ ctrl_globals.json.currentStatus.agentSettings.apiKey }}"

- name: Install the NGINX Controller agent
  include_role:
    name: nginxinc.nginx_controller_agent
  vars:
    api_key: "{{ api_key }}"