---
apiVersion: v1
kind: Deployment
metadata:
  namespace: upstream2
  labels:
    app: nginx-upstream2
  name: nginx-upstream2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-upstream2
  template:
    metadata:
      labels:
        app: nginx-upstream2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-upstream2
  dnsPolicy: ClusterFirst
  restartPolicy: Always