---
# controller_auth_token: output by previous role in example
api_version: "api/v1"
license: "/tmp/controller_license.base64.txt"
controller_bucket: "tky-nginx-ctlr-v3-demo"
controller_license_bucket_path: "controller_license.txt" 
controller_license_local_path: "/tmp/controller_license.txt"
ansible_become_password: "{{ lookup('env', 'NGINX_SU_PASS') }}"