---

# Using gsutil (part of google sdk) command to download the files as other modules fail
# First, authenticate with the service account credentials
- name: Activate gcloud auth with service account json
  shell: gcloud auth activate-service-account --key-file /drone/src/gcp/gcp_creds.json
  delegate_to: localhost

# Download the controller license file to the localhost (Ansible controller) /tmp
- name: Download controller license file to Ansible controller
  shell: gsutil cp gs://{{ controller_bucket }}/{{ controller_license_bucket_path }} {{ controller_license_local_path }}
  register: ctlr_license
  delegate_to: localhost

# - debug:
#     var: license_body

# - debug: 
#     msg: "{{ lookup('template', '{{ role_path }}/templates/license.tpl') }}"

# License file is already downloaded in /tmp dir from nginx_ctlr_initialize role
# body content will be formatted in json, which is the expected key/value by NGINX controller
- name: POST from contents of file
  uri:
    url: "https://{{ controller.fqdn }}/{{ api_version }}/platform/license-file"
    method: POST
    body_format: json
    body: 
      content: "{{ license_body }}"
    return_content: true
    status_code: 200
    validate_certs: false
    headers:
      Cookie: "{{ controller.auth_token }}"
  register: controller_response
    
# Get status of licensing task
- name: GET NGINX Controller license status
  uri:
    url: "https://{{ controller.fqdn }}/{{ api_version }}/platform/license"
    method: GET
    status_code: 200
    validate_certs: false
    headers:
      Cookie: "{{ controller.auth_token }}"
  register: controller_license